### ISSUE TITLE
[discuss] What do you want in DDDplus 1.2.0

### ISSUE THREAD

**Issue by funkygao** [funkygao/cp-ddd-framework#17]
The purpose of this issue is to discuss what you think should be added in DDDplus 1.2.0, such as features, bugfixes for known problems, and code refactoring optimizations.

**Comment by funkygao** [comment]
add specification & notification pattern support #19

**Comment by funkygao** [comment]
故障追溯功能

**Comment by funkygao** [comment]
https://gitter.im/cp-ddd-framework/community?at=5fa27afa8a236947ba84dabc

integration with BPM

**Comment by funkygao** [comment]
## 全链路视角的需求管理机制，提高协同效率

在产业互联网的大背景下，2B业务，一个需求往往从上到下触发企业各个系统的协同开发

**Comment by funkygao** [comment]
### 异常管理

**Comment by funkygao** [comment]
### 业务运营

- 按业务维度进行故障监控
- 单元化部署
- 维稳保障，QoS

**Comment by funkygao** [comment]
manageable async step execution #24

**Comment by 422053362** [comment]
需要一个可视化的编排页面
