### ISSUE TITLE
扩展点执行超时，之前执行的步骤是否需要回滚

### ISSUE THREAD

**Issue by littlebingo** [funkygao/cp-ddd-framework#34]
ExtensionInvocationHandler这个类的invokeExtensionMethodWithTimeout方法会捕获TimeoutException异常，那么之前执行的步骤没有回滚是否会有问题？

**Comment by funkygao** [comment]
它会捕获TimeoutException，并抛出 ExtTimeoutException(extends RuntimeException)，StepsExecTemplate 看到RuntimeException，就会回滚的

**Comment by funkygao** [comment]
可以写个test case，专门针对这个验证一下

**Comment by littlebingo** [comment]
用你的demo项目测试了一下，并没有回滚。

// 其他异常，best effort rollback if necessary
            if (!executedSteps.empty() && cause instanceof RuntimeException) {
                if (cause.getClass() == resolveStepExType()) { // Step必定是同一个ClassLoader加载的：中台统一加载
                    // 如果是Step的泛型里定义的异常，则回滚：回滚都是同步的
                    safeRollbackExecutedSteps(model, (RuntimeException) cause, executedSteps);
                } else {
                    // 其他类异常不回滚
                    log.debug("will not rollback, {} thrown", cause.getClass().getCanonicalName());
                }
            }

resolveStepExType这个方法判断了是否是OrderException，其他的RuntimeException都忽略掉了

**Comment by funkygao** [comment]
OK，我先补一个测试用例，验证一下

**Comment by funkygao** [comment]
确实不回顾，StepsExecTemplate里的设计：

// 如果是Step的泛型里定义的异常，则回滚：回滚都是同步的

即，抛出FooException才回滚，ExtTimeoutException 是不回滚的，抛出到外面

ExtTimeoutException，属于未知状态，不确定状态，框架不敢做回滚动作，所以交给上层了：由使用者决定

**Comment by funkygao** [comment]
https://github.com/funkygao/cp-ddd-framework/blob/c2c5341b40b2d9823e4be461a180801acaa6ac4f/dddplus-runtime/src/main/java/io/github/dddplus/runtime/StepsExecTemplate.java#L154
