### ISSUE TITLE
Failed to execute 'mvn test' with 1.1.0-RELEASE and current master branch

### ISSUE THREAD

**Issue by tohlzhu** [funkygao/cp-ddd-framework#41]
Failed to execute 'mvn test' with 1.1.0-RELEASE and current master branch, here is the output:

[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ArchitectureEnforcerTest.optionalInterfaceNameStartsWithI:55 expected:<... violated (5 times):[
simple name of io.github.dddplus.runtime.registry.mock.ability.AbilityTag does not start with 'I' in (AbilityTag.java:0)
simple name of io.github.dddplus.runtime.registry.mock.pattern.Patterns does not start with 'I' in (Patterns.java:0)
simple name of io.github.dddplus.runtime.registry.mock.step.Steps does not start with 'I' in (Steps.java:0)
simple name of io.github.dddplus.runtime.registry.mock.step.Steps$Cancel does not start with 'I' in (Steps.java:0)]
simple name of io.g...> but was:<... violated (5 times):[
simple name of io.github.dddplus.runtime.registry.mock.ability.AbilityTag does not start with 'I' in (AbilityTag.java:0)
simple name of io.github.dddplus.runtime.registry.mock.pattern.Patterns does not start with 'I' in (Patterns.java:0)
simple name of io.github.dddplus.runtime.registry.mock.step.Steps does not start with 'I' in (Steps.java:0)
]imple name of io.github.dddplus.runtime.registry.mock.step.Steps$Cancel does not start with 'I' in (Steps.java:0)
simple name of io.g...>
[INFO]
[ERROR] Tests run: 85, Failures: 1, Errors: 0, Skipped: 1

**Comment by funkygao** [comment]
2e9c42dd02553fb0682cccfd6343efdb274254f2

**Comment by funkygao** [comment]
@tohlzhu  Can you please check it again?

I cannot reproduce this issue

**Comment by tohlzhu** [comment]
The new commit worked, BUILD SUCCESS!

**Comment by tohlzhu** [comment]
Thanks a lot!
