### ISSUE TITLE
PluginApplicationContext和ContainerApplicationContext隔离性

### ISSUE THREAD

**Issue by wanziyao** [funkygao/cp-ddd-framework#44]
PluginApplicationContext作为containerApplicationContext的子容器，在plugin的component bean里面可以获取spring的任意bean，这样隔离性不太好，如果是plugin里面直接获取dao，调用dao的方法访问数据库，就可以绕过中台的保护

**Comment by funkygao** [comment]
是的，目前提供给了扩展包IContainerContext接口，里面提供了getBean方法，主要是考虑提供前台更大的灵活性：让前台可以复用中台的spring bean。
你说的问题确实存在，DDDplus应该让使用者提供处理ConainerContext之外的IContainerContext实现，而不是写死只能使用ContainerContext
