### ISSUE TITLE
类库看起有点复杂

### ISSUE THREAD

**Issue by spyvip** [funkygao/cp-ddd-framework#6]
类库、示例看起来有点复杂

示例如何启动？如何观察相关现象表示运行ok

有生产在使用吗？

**Comment by funkygao** [comment]
是的，在生产环境下使用的，用了近1年了，在多个中台项目里使用。

但热加载的Plugin机制还在开发中，生产环境没有使用。

很好的建议，感谢！示例代码还很不完善，我会很快改进

**Comment by spyvip** [comment]
@funkygao 看起来很实用的，方便加个钉钉啥的吗？深入交流交流

**Comment by funkygao** [comment]
不使用钉钉，可以使用gitter https://gitter.im/cp-ddd-framework/community

**Comment by funkygao** [comment]
@spyvip 说明文档里，增加了一个“快速入门”的章节：https://github.com/funkygao/cp-ddd-framework#quickstart

有空帮看一下，提提意见，thanks

**Comment by funkygao** [comment]
![image](https://user-images.githubusercontent.com/667048/94458232-42d18580-01e8-11eb-9dfd-659da477bb57.png)

简化了一下
